// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdkkpxtbipwtxmpetwwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZka2tweHRiaXB3dHhtcGV0d3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTMyMTQsImV4cCI6MjA3Mzk2OTIxNH0.nE2t_vQPQZHfg3xoUsgUPMZZyLOgR3TviVL6iw_5v8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
